--Q1
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product VARCHAR(50),
    category VARCHAR(50)
);

INSERT INTO products (product_id, product, category) VALUES
(1, 'LAPTOP', 'ELECTRONICS'),
(2, 'SMARTPHONE', 'ELECTRONICS'),
(3, 'TABLETS', 'ELECTRONICS'),
(9, 'PRINTER', 'ELECTRONICS'),
(4, 'HEADPHONES', 'ACCESSORIES'),
(5, 'SMARTWATCH', 'ACCESSORIES'),
(6, 'KEYBOARD', 'ACCESSORIES'),
(7, 'MOUSE', 'ACCESSORIES'),
(8, 'MONITOR', 'ACCESSORIES');

WITH PROD_DATA AS(
SELECT  product, category,  
ROW_() OVER (PARTITION BY CATEGORY ORDER BY PRODUCT_ID, CATEGORY DESC) AS PRODUCT_ID
FROM PRODUCTS
)

SELECT product_id, product, category FROM PROD_DATA;

--Q2
